# Generated by Django 4.2.7 on 2024-01-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofisdle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfisdle',
        ),
    ]
