# Generated by Django 4.2.7 on 2024-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0002_elvstunis_rename_dre_dretunis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dretunis',
            name='dre_id_in_cnte',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
