# Generated by Django 4.2.7 on 2024-03-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0003_alter_dretunis_dre_id_in_cnte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elvstunis',
            name='classe',
        ),
        migrations.AddField(
            model_name='ecolestunis',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ClassTunis',
        ),
    ]
