# Generated by Django 4.2.7 on 2024-03-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0004_remove_elvstunis_classe_ecolestunis_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTunis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('class_level', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('level', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tunis.ecolestunis')),
            ],
            options={
                'unique_together': {('cid', 'ecole')},
            },
        ),
        migrations.AddField(
            model_name='elvstunis',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tunis.classtunis'),
        ),
    ]
