# Generated by Django 4.2.7 on 2024-03-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0005_classtunis_elvstunis_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtunis',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='Tunis.ecolestunis'),
        ),
    ]
