# Generated by Django 4.2.7 on 2024-03-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0006_alter_classtunis_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecolestunis',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
