# Generated by Django 4.2.7 on 2024-03-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0007_alter_ecolestunis_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtunis',
            name='class_level',
        ),
    ]
