# Generated by Django 4.2.7 on 2024-03-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0009_ecolestunis_extracted_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtunis',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
