# Generated by Django 4.2.7 on 2024-03-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0010_alter_classtunis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElvsTunis0',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=200)),
                ('dirty_name', models.CharField(max_length=200)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tunis.classtunis')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tunis.ecolestunis')),
            ],
        ),
    ]
