# Generated by Django 4.2.7 on 2024-03-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tunis', '0011_elvstunis0'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElvsTunis0',
            new_name='ElvsTunis11',
        ),
    ]
