# Generated by Django 4.2.7 on 2024-01-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('x', '0020_remove_del1_password_remove_del1_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='excelsheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField()),
                ('nom_prenom', models.CharField(max_length=200)),
                ('nom_pere', models.CharField(max_length=200)),
                ('date_naissance', models.CharField(max_length=11)),
                ('level', models.CharField(max_length=11)),
                ('prev_ecole', models.CharField(max_length=200)),
                ('prev_ecole_id', models.IntegerField()),
                ('Del1', models.CharField(max_length=200)),
                ('next_ecole', models.CharField(max_length=200)),
                ('next_ecole_id', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('decision', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=200)),
                ('date_downloaded', models.DateField(blank=True, null=True)),
                ('dre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='x.dre')),
            ],
        ),
    ]
