# Generated by Django 4.2.7 on 2024-01-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelsheets',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='excelsheets',
            name='uid',
            field=models.PositiveBigIntegerField(),
        ),
    ]
