# Generated by Django 4.2.7 on 2024-01-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_alter_excelsheets_comments_alter_excelsheets_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelsheets',
            name='date_naissance',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='excelsheets',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='excelsheets',
            name='prev_ecole',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
