# Generated by Django 4.2.7 on 2023-11-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elvsprep',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('nom_pere', models.CharField(max_length=200)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='x.adminecoledata2')),
            ],
        ),
    ]
