# Generated by Django 4.2.7 on 2023-11-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0002_elvsprep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elvsprep',
            name='nom_pere',
        ),
    ]
