# Generated by Django 4.2.7 on 2023-11-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0003_remove_elvsprep_nom_pere'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminecoledata2',
            name='ministre_school_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
