# Generated by Django 4.2.7 on 2023-12-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0004_adminecoledata2_ministre_school_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminEcoledata2',
            new_name='AdminEcoledata',
        ),
    ]
