# Generated by Django 4.2.7 on 2023-12-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0005_rename_adminecoledata2_adminecoledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='levelstat',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('nbr_elvs', models.PositiveSmallIntegerField(blank=True)),
                ('nbr_classes', models.PositiveSmallIntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='adminelvs',
            name='cinquieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinquieme', to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminelvs',
            name='deuxieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deuxieme', to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminelvs',
            name='premiere_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminelvs',
            name='quatrieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quatrieme', to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminelvs',
            name='sixieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixieme', to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminelvs',
            name='troisieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troisieme', to='x.levelstat'),
        ),
    ]
