# Generated by Django 4.2.7 on 2023-12-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0006_levelstat_adminelvs_cinquieme_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminelvs',
            name='cinquieme_data',
        ),
        migrations.RemoveField(
            model_name='adminelvs',
            name='deuxieme_data',
        ),
        migrations.RemoveField(
            model_name='adminelvs',
            name='premiere_data',
        ),
        migrations.RemoveField(
            model_name='adminelvs',
            name='quatrieme_data',
        ),
        migrations.RemoveField(
            model_name='adminelvs',
            name='sixieme_data',
        ),
        migrations.RemoveField(
            model_name='adminelvs',
            name='troisieme_data',
        ),
    ]
