# Generated by Django 4.2.7 on 2023-12-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0007_remove_adminelvs_cinquieme_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminecoledata',
            name='cinquieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinquieme', to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminecoledata',
            name='deuxieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deuxieme', to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminecoledata',
            name='premiere_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminecoledata',
            name='quatrieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quatrieme', to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminecoledata',
            name='sixieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sixieme', to='x.levelstat'),
        ),
        migrations.AddField(
            model_name='adminecoledata',
            name='troisieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troisieme', to='x.levelstat'),
        ),
    ]
