# Generated by Django 4.2.7 on 2023-12-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0010_alter_adminecoledata_cinquieme_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminelvs',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x.adminecoledata'),
        ),
    ]
