# Generated by Django 4.2.7 on 2023-12-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0011_alter_adminelvs_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elvsprep',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x.adminecoledata'),
        ),
    ]
