# Generated by Django 4.2.7 on 2023-12-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0012_alter_elvsprep_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminelvs',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='x.adminecoledata'),
        ),
        migrations.AlterField(
            model_name='elvsprep',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='x.adminecoledata'),
        ),
    ]
