# Generated by Django 4.2.7 on 2023-12-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0015_alter_adminelvs_ecole_alter_elvsprep_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminecoledata',
            name='cinquieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cinquieme', to='x.levelstat'),
        ),
        migrations.AlterField(
            model_name='adminecoledata',
            name='deuxieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deuxieme', to='x.levelstat'),
        ),
        migrations.AlterField(
            model_name='adminecoledata',
            name='premiere_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='x.levelstat'),
        ),
        migrations.AlterField(
            model_name='adminecoledata',
            name='quatrieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quatrieme', to='x.levelstat'),
        ),
        migrations.AlterField(
            model_name='adminecoledata',
            name='sixieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sixieme', to='x.levelstat'),
        ),
        migrations.AlterField(
            model_name='adminecoledata',
            name='troisieme_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='troisieme', to='x.levelstat'),
        ),
    ]
