# Generated by Django 4.2.7 on 2023-12-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0016_alter_adminecoledata_cinquieme_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelstat',
            name='nbr_classes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='levelstat',
            name='nbr_elvs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
