# Generated by Django 4.2.7 on 2023-12-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0017_alter_levelstat_nbr_classes_alter_levelstat_nbr_elvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelstat',
            name='nbr_classes',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
