# Generated by Django 4.2.7 on 2024-01-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0018_alter_levelstat_nbr_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='del1',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='del1',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
