# Generated by Django 4.2.7 on 2024-01-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0019_del1_password_del1_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='del1',
            name='password',
        ),
        migrations.RemoveField(
            model_name='del1',
            name='username',
        ),
        migrations.AddField(
            model_name='dre',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dre',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
