# Generated by Django 4.2.7 on 2024-02-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0021_levelstat_nbr_comming_levelstat_nbr_leaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminecoledata',
            name='del1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoles', to='x.del1'),
        ),
    ]
