# Generated by Django 4.2.7 on 2024-02-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0022_alter_adminecoledata_del1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminecoledata',
            old_name='cinquieme_data',
            new_name='cinquieme',
        ),
        migrations.RenameField(
            model_name='adminecoledata',
            old_name='deuxieme_data',
            new_name='deuxieme',
        ),
        migrations.RenameField(
            model_name='adminecoledata',
            old_name='premiere_data',
            new_name='premiere',
        ),
        migrations.RenameField(
            model_name='adminecoledata',
            old_name='quatrieme_data',
            new_name='quatrieme',
        ),
        migrations.RenameField(
            model_name='adminecoledata',
            old_name='sixieme_data',
            new_name='sixieme',
        ),
        migrations.RenameField(
            model_name='adminecoledata',
            old_name='troisieme_data',
            new_name='troisieme',
        ),
    ]
