# Generated by Django 4.2.7 on 2024-02-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0023_rename_cinquieme_data_adminecoledata_cinquieme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminecoledata',
            name='principal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
