# Generated by Django 4.2.7 on 2024-02-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0024_adminecoledata_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
