# Generated by Django 4.2.7 on 2024-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0026_tuniselvs_delete_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuniselvs',
            name='classe_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tuniselvs',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tuniselvs',
            name='uid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
