# Generated by Django 4.2.7 on 2024-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0027_alter_tuniselvs_classe_id_alter_tuniselvs_nom_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirtyNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(blank=True, null=True)),
                ('nom_prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('classe_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ecole_name', models.CharField(max_length=200)),
                ('ecole_id', models.IntegerField()),
            ],
        ),
    ]
