# Generated by Django 4.2.7 on 2024-03-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0028_dirtynames'),
    ]

    operations = [
        migrations.AddField(
            model_name='del1',
            name='dre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='x.dre'),
        ),
    ]
